#ChipScope Core Inserter Project File Version 3.0
#Sat Apr 14 15:30:45 CST 2018
Project.device.designInputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.designOutputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=5
Project.filter<0>=
Project.filter<1>=rdy_w
Project.filter<2>=rdy_r
Project.filter<3>=rdy_
Project.filter<4>=rdy
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=Gen_clk_1 clk_50m
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=uart_1 DataRX_1<0>
Project.unit<0>.dataChannel<10>=uart_1 DataRX_2<2>
Project.unit<0>.dataChannel<11>=uart_1 DataRX_2<3>
Project.unit<0>.dataChannel<12>=uart_1 DataRX_2<4>
Project.unit<0>.dataChannel<13>=uart_1 DataRX_2<5>
Project.unit<0>.dataChannel<14>=uart_1 DataRX_2<6>
Project.unit<0>.dataChannel<15>=uart_1 DataRX_2<7>
Project.unit<0>.dataChannel<16>=Ctr_UART_1 WriteEn_ADC
Project.unit<0>.dataChannel<17>=AD9244_1 rdy_W
Project.unit<0>.dataChannel<18>=AD9244_1 Addr_W<0>
Project.unit<0>.dataChannel<19>=AD9244_1 Addr_W<1>
Project.unit<0>.dataChannel<1>=uart_1 DataRX_1<1>
Project.unit<0>.dataChannel<20>=AD9244_1 Addr_W<2>
Project.unit<0>.dataChannel<21>=AD9244_1 Addr_W<3>
Project.unit<0>.dataChannel<22>=AD9244_1 Addr_W<4>
Project.unit<0>.dataChannel<23>=AD9244_1 Addr_W<5>
Project.unit<0>.dataChannel<24>=AD9244_1 Addr_W<6>
Project.unit<0>.dataChannel<25>=AD9244_1 Addr_W<7>
Project.unit<0>.dataChannel<2>=uart_1 DataRX_1<2>
Project.unit<0>.dataChannel<3>=uart_1 DataRX_1<3>
Project.unit<0>.dataChannel<4>=uart_1 DataRX_1<4>
Project.unit<0>.dataChannel<5>=uart_1 DataRX_1<5>
Project.unit<0>.dataChannel<6>=uart_1 DataRX_1<6>
Project.unit<0>.dataChannel<7>=uart_1 DataRX_1<7>
Project.unit<0>.dataChannel<8>=uart_1 DataRX_2<0>
Project.unit<0>.dataChannel<9>=uart_1 DataRX_2<1>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=26
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=uart_1 DataRX_1<0>
Project.unit<0>.triggerChannel<0><1>=uart_1 DataRX_1<1>
Project.unit<0>.triggerChannel<0><2>=uart_1 DataRX_1<2>
Project.unit<0>.triggerChannel<0><3>=uart_1 DataRX_1<3>
Project.unit<0>.triggerChannel<0><4>=uart_1 DataRX_1<4>
Project.unit<0>.triggerChannel<0><5>=uart_1 DataRX_1<5>
Project.unit<0>.triggerChannel<0><6>=uart_1 DataRX_1<6>
Project.unit<0>.triggerChannel<0><7>=uart_1 DataRX_1<7>
Project.unit<0>.triggerChannel<1><0>=uart_1 DataRX_2<0>
Project.unit<0>.triggerChannel<1><1>=uart_1 DataRX_2<1>
Project.unit<0>.triggerChannel<1><2>=uart_1 DataRX_2<2>
Project.unit<0>.triggerChannel<1><3>=uart_1 DataRX_2<3>
Project.unit<0>.triggerChannel<1><4>=uart_1 DataRX_2<4>
Project.unit<0>.triggerChannel<1><5>=uart_1 DataRX_2<5>
Project.unit<0>.triggerChannel<1><6>=uart_1 DataRX_2<6>
Project.unit<0>.triggerChannel<1><7>=uart_1 DataRX_2<7>
Project.unit<0>.triggerChannel<2><0>=Ctr_UART_1 WriteEn_ADC
Project.unit<0>.triggerChannel<3><0>=AD9244_1 rdy_W
Project.unit<0>.triggerChannel<4><0>=AD9244_1 Addr_W<0>
Project.unit<0>.triggerChannel<4><1>=AD9244_1 Addr_W<1>
Project.unit<0>.triggerChannel<4><2>=AD9244_1 Addr_W<2>
Project.unit<0>.triggerChannel<4><3>=AD9244_1 Addr_W<3>
Project.unit<0>.triggerChannel<4><4>=AD9244_1 Addr_W<4>
Project.unit<0>.triggerChannel<4><5>=AD9244_1 Addr_W<5>
Project.unit<0>.triggerChannel<4><6>=AD9244_1 Addr_W<6>
Project.unit<0>.triggerChannel<4><7>=AD9244_1 Addr_W<7>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerPortCount=4
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=8
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerPortWidth<4>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
