#ChipScope Core Inserter Project File Version 3.0
#Wed Apr 25 09:31:41 CST 2018
Project.device.designInputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg_v1_fft256\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.designOutputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg_v1_fft256\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\2_FPGA_program\\Proj_ECS_sinoagg_v1_fft256\\Proj_ECS\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=Gen_clk_1 clk_50m
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=Ctr_UART_1 DataRX_1<0>
Project.unit<0>.dataChannel<1>=Ctr_UART_1 DataRX_1<1>
Project.unit<0>.dataChannel<2>=Ctr_UART_1 DataRX_1<2>
Project.unit<0>.dataChannel<3>=Ctr_UART_1 DataRX_1<3>
Project.unit<0>.dataChannel<4>=Ctr_UART_1 DataRX_2<0>
Project.unit<0>.dataChannel<5>=Ctr_UART_1 DataRX_2<1>
Project.unit<0>.dataChannel<6>=Ctr_UART_1 DataRX_2<2>
Project.unit<0>.dataChannel<7>=Ctr_UART_1 DataRX_2<3>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=9
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=Ctr_UART_1 DataRX_1<0>
Project.unit<0>.triggerChannel<0><1>=Ctr_UART_1 DataRX_1<1>
Project.unit<0>.triggerChannel<0><2>=Ctr_UART_1 DataRX_1<2>
Project.unit<0>.triggerChannel<0><3>=Ctr_UART_1 DataRX_1<3>
Project.unit<0>.triggerChannel<1><0>=Ctr_UART_1 DataRX_2<0>
Project.unit<0>.triggerChannel<1><1>=Ctr_UART_1 DataRX_2<1>
Project.unit<0>.triggerChannel<1><2>=Ctr_UART_1 DataRX_2<2>
Project.unit<0>.triggerChannel<1><3>=Ctr_UART_1 DataRX_2<3>
Project.unit<0>.triggerChannel<2><0>=Ctr_UART_1 Err_Check
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerPortCount=3
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortWidth<0>=4
Project.unit<0>.triggerPortWidth<1>=4
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
