#ChipScope Core Inserter Project File Version 3.0
#Wed Apr 18 17:48:04 CST 2018
Project.device.designInputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.designOutputFile=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\Proj_ECS_cs.ngc
Project.device.deviceFamily=18
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\2_FPGA_program\\Proj_ECS_sinoagg\\Proj_ECS\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=Gen_clk_1 clk_50m
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=Ctr_UART_1 DataRX_1<0>
Project.unit<0>.dataChannel<10>=Ctr_UART_1 DataRX_2<2>
Project.unit<0>.dataChannel<11>=Ctr_UART_1 DataRX_2<3>
Project.unit<0>.dataChannel<12>=Ctr_UART_1 DataRX_2<4>
Project.unit<0>.dataChannel<13>=Ctr_UART_1 DataRX_2<5>
Project.unit<0>.dataChannel<14>=Ctr_UART_1 DataRX_2<6>
Project.unit<0>.dataChannel<15>=Ctr_UART_1 DataRX_2<7>
Project.unit<0>.dataChannel<16>=AD9244_1 WriteEn
Project.unit<0>.dataChannel<17>=AD9244_1 rdy_W
Project.unit<0>.dataChannel<18>=AD9244_1 ReadEn
Project.unit<0>.dataChannel<19>=AD9244_1 rdy_R
Project.unit<0>.dataChannel<1>=Ctr_UART_1 DataRX_1<1>
Project.unit<0>.dataChannel<20>=Ctr_UART_1 Err_Check
Project.unit<0>.dataChannel<2>=Ctr_UART_1 DataRX_1<2>
Project.unit<0>.dataChannel<3>=Ctr_UART_1 DataRX_1<3>
Project.unit<0>.dataChannel<4>=Ctr_UART_1 DataRX_1<4>
Project.unit<0>.dataChannel<5>=Ctr_UART_1 DataRX_1<5>
Project.unit<0>.dataChannel<6>=Ctr_UART_1 DataRX_1<6>
Project.unit<0>.dataChannel<7>=Ctr_UART_1 DataRX_1<7>
Project.unit<0>.dataChannel<8>=Ctr_UART_1 DataRX_2<0>
Project.unit<0>.dataChannel<9>=Ctr_UART_1 DataRX_2<1>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=16
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=Ctr_UART_1 DataRX_1<0>
Project.unit<0>.triggerChannel<0><1>=Ctr_UART_1 DataRX_1<1>
Project.unit<0>.triggerChannel<0><2>=Ctr_UART_1 DataRX_1<2>
Project.unit<0>.triggerChannel<0><3>=Ctr_UART_1 DataRX_1<3>
Project.unit<0>.triggerChannel<0><4>=Ctr_UART_1 DataRX_1<4>
Project.unit<0>.triggerChannel<0><5>=Ctr_UART_1 DataRX_1<5>
Project.unit<0>.triggerChannel<0><6>=Ctr_UART_1 DataRX_1<6>
Project.unit<0>.triggerChannel<0><7>=Ctr_UART_1 DataRX_1<7>
Project.unit<0>.triggerChannel<1><0>=Ctr_UART_1 DataRX_2<0>
Project.unit<0>.triggerChannel<1><1>=Ctr_UART_1 DataRX_2<1>
Project.unit<0>.triggerChannel<1><2>=Ctr_UART_1 DataRX_2<2>
Project.unit<0>.triggerChannel<1><3>=Ctr_UART_1 DataRX_2<3>
Project.unit<0>.triggerChannel<1><4>=Ctr_UART_1 DataRX_2<4>
Project.unit<0>.triggerChannel<1><5>=Ctr_UART_1 DataRX_2<5>
Project.unit<0>.triggerChannel<1><6>=Ctr_UART_1 DataRX_2<6>
Project.unit<0>.triggerChannel<1><7>=Ctr_UART_1 DataRX_2<7>
Project.unit<0>.triggerChannel<2><0>=AD9244_1 WriteEn
Project.unit<0>.triggerChannel<3><0>=AD9244_1 rdy_W
Project.unit<0>.triggerChannel<4><0>=AD9244_1 ReadEn
Project.unit<0>.triggerChannel<5><0>=AD9244_1 rdy_R
Project.unit<0>.triggerChannel<6><0>=Ctr_UART_1 Err_Check
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerPortWidth<1>=8
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerPortWidth<4>=1
Project.unit<0>.triggerPortWidth<5>=1
Project.unit<0>.triggerPortWidth<6>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
