######################################################################
##
## Filename: tb_ecs_project.udo
## Created on: Tue Apr 10 9:27:32 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
