######################################################################
##
## Filename: tb_uart.udo
## Created on: Tue Apr 10 17:35:55 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
